apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/dns01-provider: "cloudflare"
  namespace: kuma
  name: kuma-gw
spec:
  gatewayClassName: eg
  infrastructure:
    annotations:
      metallb.universe.tf/address-pool: ipv6-default
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "uptime.br0.no"
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: kuma-secret