apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  parentRefs:
    - name: kuma-gw
      namespace: default
  hostnames:
    - "uptime.br0.no"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: uptime-kuma-service
          port: 3001
