apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data-01
  namespace: kuma
  annotations:
    nfs.io/storage-path: "kuma-data-01"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
