apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
